# Get the full explanation of the config values at: https://pastebin.com/v9PPj4fk
# Similarity Score is a score between 0 and 1 which will determine how similar an answer must be for it to be recognized recognized right. Value of 1 requires exact answer, value of 0.8 requires close answer.
Similarity score: 0.85

# Default time per round is the default value for the maximum amount of time (in seconds) players will have to answer a question.
Default time per round: 15

# Default rounds is the default value for the total number of rounds in a game.
Default rounds: 10

# Time between rounds is for the transition time (in seconds) between the questions themselves.
Time between rounds: 3

# Top winner amount's value will show up to these many winners displayed in chat after a trivia game.
Top winner amount: 3

# Scheduled games, if true, will let console automatically host trivia every x minutes.
Scheduled games: false

# Scheduled games interval is the time between the scheduled games (in minutes) if scheduled games are enabled.
Scheduled games interval: 60

# Scheduled games minimum players is the minimum number of players that must be on for scheduled trivia events to be hosted.
Scheduled games minimum players: 6

# Enabling boss bar will display a progress bar on the top of the screen as the game goes on.
Enable boss bar: true

# The remaining values are to adjust the sounds that are played during Trivia.
# You can adjust the type of sound, pitch and volume of what's played after an event during a game
# for instance, when a player answers a question, they get played a block note sound by default
# Use sound values found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html

# Answer correct sound will be played after a player answers the question correctly. Enter 'none' to play no sound.
Answer correct:
  sound: BLOCK_NOTE_BLOCK_PLING
  volume: 0.6
  pitch: 1.5

Question skipped:
  sound: BLOCK_ANVIL_BREAK
  volume: 0.6
  pitch: 1.0

# Time up sound will be played after no one has answered the question correctly in time.
Time up:
  sound: ENTITY_VILLAGER_NO
  volume: 0.6
  pitch: 0.9

# Game start sound will be played when the trivia game starts.
Game start:
  sound: ENTITY_PLAYER_LEVELUP
  volume: 0.6
  pitch: 1.0

# Game over sound will be played after the trivia game is over.
Game over:
  sound: ENTITY_PLAYER_LEVELUP
  volume: 0.6
  pitch: 0.9

# This is to keep track of what config version this is. Do not modify!
Config Version: 6