name: Trivia
version: "1.11"
main: me.marcarrots.trivia.Trivia
api-version: 1.16
authors: [ MarCarrot ]
description: Trivia plugin for Minecraft Spigot
softdepend:
  - Vault
permissions:
  trivia.admin:
    default: op
commands:
  trivia:
    description: Main trivia command.
    permission: trivia.admin
